"""
Invoice router — all CRUD and lifecycle endpoints for the invoices module.

Endpoints
---------
GET    /invoices                      List invoices (paginated, filterable)
POST   /invoices                      Create a new draft invoice
GET    /invoices/public/{token}       Public view (no auth required)
GET    /invoices/{id}                 Get single invoice
PUT    /invoices/{id}                 Update draft invoice
DELETE /invoices/{id}                 Delete draft invoice
POST   /invoices/{id}/send            Send invoice to client
POST   /invoices/{id}/mark-paid       Mark invoice as paid
POST   /invoices/{id}/duplicate       Duplicate invoice as new draft
GET    /invoices/{id}/pdf             Download invoice PDF
"""

import logging

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse, JSONResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import get_current_user
from app.exceptions import AppException
from app.services import subscription_service
from app.models.invoice import InvoiceStatus
from app.models.user import User
from app.schemas.invoice import (
    InvoiceCreate,
    InvoiceListResponse,
    InvoiceResponse,
    InvoiceUpdate,
)
from app.services import invoice_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/invoices", tags=["Invoices"])


# ---------------------------------------------------------------------------
# List / collection endpoints
# ---------------------------------------------------------------------------


@router.get("", response_model=InvoiceListResponse, summary="List invoices")
async def list_invoices(
    status: InvoiceStatus | None = Query(None, description="Filter by invoice status"),
    client_id: int | None = Query(None, description="Filter by client ID"),
    skip: int = Query(0, ge=0, description="Number of records to skip"),
    limit: int = Query(50, ge=1, le=200, description="Maximum records to return"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceListResponse:
    """Return a paginated list of the authenticated user's invoices."""
    items, total = invoice_service.get_invoices(
        db, current_user.id, status, client_id, skip, limit
    )
    return InvoiceListResponse(items=items, total=total)


@router.post(
    "",
    response_model=InvoiceResponse,
    status_code=201,
    summary="Create invoice",
)
async def create_invoice(
    data: InvoiceCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """
    Create a new draft invoice.

    The ``invoice_number`` and ``public_token`` are auto-generated by the server.
    All monetary totals (subtotal, tax_amount, total) are computed server-side.
    Enforces the user's monthly invoice limit based on their subscription plan.
    """
    try:
        subscription_service.check_invoice_limit(db, current_user)
    except AppException as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)

    invoice = invoice_service.create_invoice(db, current_user.id, data)
    subscription_service.increment_invoice_count(db, current_user)
    return invoice


# ---------------------------------------------------------------------------
# Public endpoint (no authentication)
# ---------------------------------------------------------------------------


@router.get(
    "/public/{token}",
    response_model=InvoiceResponse,
    summary="Get invoice by public token",
)
async def get_public_invoice(
    token: str,
    db: Session = Depends(get_db),
) -> InvoiceResponse:
    """
    Retrieve an invoice using its public UUID token.

    This endpoint is intentionally unauthenticated so that clients can view
    their invoices without an account. The token is included in every invoice
    email sent by the system.
    """
    return invoice_service.get_invoice_by_token(db, token)


# ---------------------------------------------------------------------------
# Single-resource CRUD
# ---------------------------------------------------------------------------


@router.get(
    "/{invoice_id}",
    response_model=InvoiceResponse,
    summary="Get invoice",
)
async def get_invoice(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """Retrieve a single invoice by ID (must belong to the authenticated user)."""
    return invoice_service.get_invoice(db, invoice_id, current_user.id)


@router.put(
    "/{invoice_id}",
    response_model=InvoiceResponse,
    summary="Update invoice",
)
async def update_invoice(
    invoice_id: int,
    data: InvoiceUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """
    Partially update a draft invoice.

    Only DRAFT invoices may be updated. Attempting to edit a sent, paid,
    overdue, or cancelled invoice returns HTTP 409.
    """
    return invoice_service.update_invoice(db, invoice_id, current_user.id, data)


@router.delete(
    "/{invoice_id}",
    status_code=204,
    summary="Delete invoice",
)
async def delete_invoice(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> None:
    """
    Permanently delete a draft invoice.

    Only DRAFT invoices may be deleted. Returns HTTP 409 for any other status.
    """
    invoice_service.delete_invoice(db, invoice_id, current_user.id)


# ---------------------------------------------------------------------------
# Lifecycle action endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/{invoice_id}/send",
    response_model=InvoiceResponse,
    summary="Send invoice to client",
)
async def send_invoice(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """
    Send an invoice to its client via email.

    Generates a PDF (if WeasyPrint is available), emails the client, and
    transitions the invoice status to SENT. Cancelled invoices cannot be sent.
    """
    return invoice_service.send_invoice(db, invoice_id, current_user.id)


@router.post(
    "/{invoice_id}/mark-paid",
    response_model=InvoiceResponse,
    summary="Mark invoice as paid",
)
async def mark_paid(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """
    Mark an invoice as PAID and record the payment timestamp.

    DRAFT and CANCELLED invoices cannot be marked as paid.
    """
    return invoice_service.mark_paid(db, invoice_id, current_user.id)


@router.post(
    "/{invoice_id}/duplicate",
    response_model=InvoiceResponse,
    status_code=201,
    summary="Duplicate invoice",
)
async def duplicate_invoice(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> InvoiceResponse:
    """
    Create a new DRAFT invoice copied from the given invoice.

    The duplicate receives today's issue/due dates, a fresh invoice number,
    and a new public token. The original invoice is not modified.
    """
    return invoice_service.duplicate_invoice(db, invoice_id, current_user.id)


# ---------------------------------------------------------------------------
# PDF download
# ---------------------------------------------------------------------------


@router.get("/{invoice_id}/pdf", summary="Download invoice PDF", response_model=None)
async def download_pdf(
    invoice_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> FileResponse | JSONResponse:
    """
    Download the PDF for an invoice. Generates it on demand if not yet created.
    """
    from app.services.pdf import generate_invoice_pdf

    invoice = invoice_service.get_invoice(db, invoice_id, current_user.id)

    # Generate on demand if not yet produced
    if not invoice.pdf_url:
        invoice_data: dict = {
            "invoice_number": invoice.invoice_number,
            "status": invoice.status.value,
            "issue_date": str(invoice.issue_date),
            "due_date": str(invoice.due_date),
            "client_name": invoice.client.name if invoice.client else "",
            "client_email": invoice.client.email if invoice.client else "",
            "client_company": (invoice.client.company_name or "") if invoice.client else "",
            "currency": invoice.currency,
            "subtotal": str(invoice.subtotal),
            "tax_rate": str(invoice.tax_rate),
            "tax_amount": str(invoice.tax_amount),
            "discount_amount": str(invoice.discount_amount),
            "total": str(invoice.total),
            "notes": invoice.notes,
            "items": [
                {
                    "description": item.description,
                    "quantity": str(item.quantity),
                    "unit_price": str(item.unit_price),
                    "amount": str(item.amount),
                }
                for item in invoice.items
            ],
        }
        pdf_path = generate_invoice_pdf(invoice_data)
        if not pdf_path:
            return JSONResponse(
                status_code=503,
                content={"detail": "PDF generation failed. Please try again."},
            )
        invoice.pdf_url = pdf_path
        db.commit()

    return FileResponse(
        path=invoice.pdf_url,
        media_type="application/pdf",
        filename=f"{invoice.invoice_number}.pdf",
    )
