"""
PDF generation service using WeasyPrint.

Generates a styled HTML invoice and renders it to a PDF file stored on disk.
The returned path is saved to ``Invoice.pdf_url`` and served via the download
endpoint.

If WeasyPrint is not installed the function logs a warning and returns an
empty string so the rest of the application can continue to work without it
(e.g., during local development or testing).
"""

import logging
import uuid
from pathlib import Path

from app.config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

INVOICE_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Invoice {invoice_number}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Arial, sans-serif; font-size: 14px; color: #333; padding: 40px; }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 36px; }}
  .brand {{ display: flex; flex-direction: column; gap: 4px; }}
  .invoice-title {{ font-size: 32px; font-weight: bold; color: #4F46E5; }}
  .invoice-number {{ font-size: 16px; color: #666; margin-top: 4px; }}
  .meta {{ text-align: right; line-height: 1.8; }}
  .status-badge {{
    display: inline-block; padding: 4px 14px; border-radius: 20px;
    font-size: 12px; font-weight: bold; letter-spacing: 0.5px;
    background: #e0e7ff; color: #4F46E5; margin-bottom: 8px;
  }}
  .section {{ margin-bottom: 24px; line-height: 1.7; }}
  .section strong {{ display: block; margin-bottom: 4px; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 24px 0; }}
  thead th {{
    background: #4F46E5; color: #fff; padding: 12px 10px;
    text-align: left; font-size: 13px; font-weight: 600;
  }}
  thead th:last-child {{ text-align: right; }}
  tbody td {{ padding: 10px; border-bottom: 1px solid #eee; vertical-align: top; }}
  tbody td:last-child {{ text-align: right; }}
  tbody tr:last-child td {{ border-bottom: none; }}
  .totals-wrap {{ display: flex; justify-content: flex-end; margin-top: 8px; }}
  .totals {{ width: 320px; border-collapse: collapse; }}
  .totals td {{ padding: 8px 10px; font-size: 14px; }}
  .totals td:last-child {{ text-align: right; font-weight: 600; }}
  .totals tr.divider td {{ border-top: 1px solid #ddd; padding-top: 10px; }}
  .totals tr.total-row td {{
    font-size: 16px; background: #f0f4ff; color: #4F46E5;
    font-weight: 700; padding: 12px 10px;
  }}
  .notes {{ margin-top: 32px; padding: 16px; background: #f9fafb; border-left: 4px solid #4F46E5; border-radius: 4px; }}
  .notes strong {{ display: block; margin-bottom: 8px; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }}
  .footer {{ margin-top: 48px; text-align: center; color: #aaa; font-size: 12px; }}
</style>
</head>
<body>
  <div class="header">
    <div class="brand">
      <div class="invoice-title">RemindInvoice</div>
      <div class="invoice-number">Invoice # {invoice_number}</div>
    </div>
    <div class="meta">
      <div><span class="status-badge">{status}</span></div>
      <div><strong>Issue Date:</strong> {issue_date}</div>
      <div><strong>Due Date:</strong> {due_date}</div>
    </div>
  </div>

  <div class="section">
    <strong>Bill To</strong>
    {client_name}<br>
    {client_email}<br>
    {client_company_line}
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:50%">Description</th>
        <th style="width:15%;text-align:right">Qty</th>
        <th style="width:17.5%;text-align:right">Unit Price</th>
        <th style="width:17.5%">Amount</th>
      </tr>
    </thead>
    <tbody>
      {items_html}
    </tbody>
  </table>

  <div class="totals-wrap">
    <table class="totals">
      <tr>
        <td>Subtotal</td>
        <td>{currency} {subtotal}</td>
      </tr>
      {tax_row}
      {discount_row}
      <tr class="divider total-row">
        <td>Total</td>
        <td>{currency} {total}</td>
      </tr>
    </table>
  </div>

  {notes_section}

  <div class="footer">Generated by RemindInvoice &mdash; {invoice_number}</div>
</body>
</html>
"""

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_invoice_pdf(invoice_data: dict) -> str:
    """
    Render an invoice dict to a PDF file and return the absolute file path.

    The file is written to ``{settings.UPLOAD_DIR}/pdfs/``. The directory
    is created automatically when it does not yet exist.

    :param invoice_data: Dictionary containing all invoice fields (see
        ``invoice_service.send_invoice`` for the exact shape).
    :returns: Absolute path of the generated PDF, or an empty string when
        WeasyPrint is unavailable.
    :raises OSError: If the PDF directory cannot be created or the file
        cannot be written.
    """
    try:
        from weasyprint import HTML  # type: ignore[import-untyped]
    except ImportError:
        logger.warning(
            "WeasyPrint is not installed — skipping PDF generation for invoice %s. "
            "Install it with: pip install weasyprint",
            invoice_data.get("invoice_number", "UNKNOWN"),
        )
        return ""

    # ------------------------------------------------------------------
    # Build items rows
    # ------------------------------------------------------------------
    items_html_parts: list[str] = []
    for item in invoice_data.get("items", []):
        items_html_parts.append(
            f"<tr>"
            f"<td>{item['description']}</td>"
            f"<td style='text-align:right'>{item['quantity']}</td>"
            f"<td style='text-align:right'>{invoice_data['currency']} {item['unit_price']}</td>"
            f"<td>{invoice_data['currency']} {item['amount']}</td>"
            f"</tr>"
        )
    items_html = "\n      ".join(items_html_parts) if items_html_parts else (
        "<tr><td colspan='4' style='color:#999'>No items</td></tr>"
    )

    # ------------------------------------------------------------------
    # Optional rows (tax / discount)
    # ------------------------------------------------------------------
    tax_row = ""
    if float(invoice_data.get("tax_rate", 0)) > 0:
        tax_row = (
            f"<tr>"
            f"<td>Tax ({invoice_data['tax_rate']}%)</td>"
            f"<td>{invoice_data['currency']} {invoice_data['tax_amount']}</td>"
            f"</tr>"
        )

    discount_row = ""
    if float(invoice_data.get("discount_amount", 0)) > 0:
        discount_row = (
            f"<tr>"
            f"<td>Discount</td>"
            f"<td>&minus;{invoice_data['currency']} {invoice_data['discount_amount']}</td>"
            f"</tr>"
        )

    notes_section = ""
    if invoice_data.get("notes"):
        notes_section = (
            f"<div class='notes'>"
            f"<strong>Notes</strong>"
            f"{invoice_data['notes']}"
            f"</div>"
        )

    client_company_line = invoice_data.get("client_company", "")
    if client_company_line:
        client_company_line = f"{client_company_line}<br>"

    # ------------------------------------------------------------------
    # Render template
    # ------------------------------------------------------------------
    html_content = INVOICE_HTML_TEMPLATE.format(
        invoice_number=invoice_data["invoice_number"],
        status=invoice_data["status"].upper(),
        issue_date=invoice_data["issue_date"],
        due_date=invoice_data["due_date"],
        client_name=invoice_data["client_name"],
        client_email=invoice_data["client_email"],
        client_company_line=client_company_line,
        items_html=items_html,
        currency=invoice_data["currency"],
        subtotal=invoice_data["subtotal"],
        tax_row=tax_row,
        discount_row=discount_row,
        total=invoice_data["total"],
        notes_section=notes_section,
    )

    # ------------------------------------------------------------------
    # Write PDF to disk
    # ------------------------------------------------------------------
    upload_dir = Path(settings.UPLOAD_DIR) / "pdfs"
    upload_dir.mkdir(parents=True, exist_ok=True)

    safe_number = invoice_data["invoice_number"].replace("-", "_").replace("/", "_")
    unique_suffix = uuid.uuid4().hex[:8]
    filename = f"invoice_{safe_number}_{unique_suffix}.pdf"
    pdf_path = str(upload_dir / filename)

    HTML(string=html_content).write_pdf(pdf_path)
    logger.info("PDF generated: %s", pdf_path)
    return pdf_path
